### ISSUE TITLE
용감한 연습문제

### ISSUE THREAD

**Issue by KoEonYack** [Woohwahwa/baekjoon#13]
@Woohwahwa 반가워요~

서류를 제출하고 코딩테스트 메일을 받기전까지 1주일 정도 시간이 있을꺼에요!
그전까지 공부해볼 내용을 슥슥 가져와봤어요!

https://programmers.co.kr/learn/challenges 
- Lv 1: 기존에 풀었던 문제 제외, 너무 수학문제 제외(최대공약수,,, 등등), SQL 문제 제외, Kakao 문제 필수!
- Lv 2: 풀수 있는선에서 풀어보아요~

Lv1이랑 Lv2랑 차이가 좀 날꺼에요.
경력 코딩테스트는 보통 코딜리티와 같은 해외 코딩테스트 사이트를 이용해요. 영어 실력을 간접적으로 볼 수 있기 때문일까요?
백준과 다르게 코딜리티, 프로그래머스는 함수의 인자로 주어지는 값을 정확하게 Output하는 방식이에요!

**Comment by leedoopal** [comment]
헉 이걸 지금봤어여..! 세상에 너무 고마워여!!!!

**Comment by leedoopal** [comment]
아 저는 챌린지가 아니라 실력체크를 풀었네여;; 머쓱해보아여;;;

**Comment by KoEonYack** [comment]
머씈 성화!

![image](https://user-images.githubusercontent.com/28642484/103284987-2c71da80-4a20-11eb-91ed-8b833a87d6a8.png)

이거 아닌가요?!?!

**Comment by KoEonYack** [comment]
앗,,, 실력체크!! 하치만 잘해써요!!

**Comment by KoEonYack** [comment]
알고리즘 뿐만 아니라 기술 면접 준비도 해야하는데요!!

https://github.com/baeharam/Must-Know-About-Frontend#fire-javascript
https://github.com/Febase/FeBase

요 두 곳을 참고하세요!

**Comment by leedoopal** [comment]
헉 너무너무 고마워요!!!!! 그동안 문제풀고 있었어용🐥

**Comment by KoEonYack** [comment]
🐥 자신감 넘치지는 노랭이 친구군요! 멋쪄요!!!
