### ISSUE TITLE
1003, 1408, 2748, 5565

### ISSUE THREAD

**Issue by leedoopal** [Woohwahwa/baekjoon#3]
### 1003

새로 풀었는데 런타임 에러가 나와요.... 이유를 알 수 없어요.......
<br/><br/>

### 1408

이것두 간단한 방법으로 새로 풀었는데 틀렸다고 나와요.....이번엔 여러번 테스트 해봤는데 이유를 알 수 없어요.....
<br/><br/>

### 2748

1003번과 같은 피보나치인데 틀렸다고 나와요.. 아무리 봐도 맞는데 왜 틀렸는지 모르겠어요
<br/><br/>

### 5565
숫자를 출력하면 되는 간단한 문제인데 런타임 에러라고 나와요..... 이유를 알 수 없어요....

<br/><br/><br/>

😢😢😢 많은 점들과 이슈를 남겨 미안해요😢😢😢😢😢

**Comment by KoEonYack** [comment]
@Woohwahwa 

제가 생각을 해보았어요~
자바스크립트를 잘 몰라서 헛다리를 짚을 수 있답니다 ㅠ&ㅠ

## 1003번 

`const input = require('fs').readFileSync('/dev/stdin').toString().map(Number);` 로 입력을 받는 코드를 작성했어요! 

제가 어제 알려준 코드에는 split 코드가 들어가있어요!!
`var input = fs.readFileSync('./dev/stdin').toString().split('\n').map(Number);`
그래서 shift과정에서 정상적으로 동작하지 않은 것 같은데 어떻게 생각하나요?? ㅠㅠ

**Comment by KoEonYack** [comment]
## 1408 

헉 정성껏 풀었는데 통과가 안되네요! 
여전히 3번 나누는 과정이 들어가 있어서 오차가 생기는게 아닐까 생각이 들어요.

제가 예전에 풀 때는 나눗셈이 들어가지 않도록 초를 1씩 더하는 방법으로 풀었어요!
파이썬 코드지만 쉬우니깐 얼추 살펴보아요~

```python
h1, m1, s1 = map(int, input().split(":"))
h2, m2, s2 = map(int, input().split(":"))

t = 0
while h1 != h2 or m1 != m2 or s1 != s2:
    s1 += 1
    t += 1
    if s1 == 60:
        s1 = 0
        m1 += 1
        if m1 == 60:
            m1 = 0
            h1 += 1
            if h1 == 24:
                h1 = 0
```

**Comment by KoEonYack** [comment]
# 2748

fibo의 N항이 90이면 자릿수가 상당히 클꺼에요! 
JS의 int의 범위는 32비트의 경우 약  -2^31 ~ 2^31 일꺼에요! 그런데 fibo의 N항이 뚫어버릴거기 때문에   
[BigInt 친구를 소개할께요!](https://frontdev.tistory.com/entry/JS-8%EB%B2%88%EC%A7%B8-%EB%8D%B0%EC%9D%B4%ED%84%B0-%ED%83%80%EC%9E%85-BigInt) 값이 커지면 잘 사용해보세요!
fibo항의 갯수에 따라서 몇 개의 자리수가 나오는지 궁금할 수 있어요! 그거는 [요기](https://temp123.tistory.com/64) 코드를 이용하면 알 수 있답니다!

```javascript
const input = parseInt(require("fs").readFileSync("/dev/stdin").toString());
const arr = [0, 1];

const fibo = (n) => {
  if (arr[n] === undefined) 
         arr[n] = BigInt(fibo(n - 1)) + BigInt(fibo(n - 2));
  return arr[n];
};

console.log(fibo(input).toString());
```

**Comment by KoEonYack** [comment]
## 5565

```javascript
const input = require('fs').readFileSync('/dev/stdin').toString().map(Number);
let T = input.shift();
```

이렇게 시도를 했더라고요! 
제 생각에는 split을 해서 배열로 변환한 다음에 split을 해야하는데 toString()을하고 바로 shift를 해서 그런것 같아요!
또한 T의 자료형은 string인데 바로 - 연산을 하더라고요! string을 무시하는 행동이에요!!

```javascript
const input = require('fs').readFileSync('/dev/stdin').toString().split('\n');;
let T = Number(input.shift());

for (let i = 0; i < 9; i++) {
  T -= parseInt(input[i]);
}

console.log(T);
```
위와같이 코드를 작성했는데 통과 되더라고요!

**Comment by leedoopal** [comment]
쌤 너무 고마워요!!!!! 1408은 아직 해결하지 못했지만 다른 것들은 쌤 덕분에 제출 했답니다🧞‍♂
