### ISSUE TITLE
2501, 2562, 2576

### ISSUE THREAD

**Issue by leedoopal** [Woohwahwa/baekjoon#8]
**2501**
홀수인 경우를 찾아서 output.push(i)를 하고 output에서 n번째로 작은 수를 찾는 문제인데 뭐가 잘못됐을까요..? 틀렸다고 나와요😔

**2562**
output에 수를 정렬한 다음 max 값을 찾았어요. 그 다음에 findIndex를 사용해서 조건에 일치하는 index를 찾아서 두개의 수를 반환해주었는데 틀렸다고 하네용..

**2576**
output에 홀수들을 push한 다음 홀수들의 합을 구한 변수 sum을 선언했어요. 그리고 그 중에서 가장 작은 값 변수 min을 선언해서 두개의 수를 반환해주었는뎅 런타임에러..!! 라고 해요😲

**Comment by KoEonYack** [comment]
## 2501

일단 int로 형변현을 안해서 이 부분을 먼저 수정해보아요!

**Comment by KoEonYack** [comment]
## 2562

문제를 잘 보면 정렬할 필요가없어요! 차례대로 주어지눈 수 중에서 순서를 찾는거에요~

**Comment by KoEonYack** [comment]
## 2576

![image](https://user-images.githubusercontent.com/28642484/102364263-98544c00-3ff9-11eb-8f8d-fbb2402a1693.png)

반례는 입력값이 전부다 짝수이면 에러가 떨어지네요!

**Comment by leedoopal** [comment]
오와아..... 쌤 2562, 2576은 덕분에 해결했어요!! 
근데 자바스크립트에서 2501은 형변환이 필요없어용! 이미 int 이거든요! 
혹시 몰라서 형변환 진행해봤는데 틀렸다고 하네용 혹시 뭐가 문제일까요..??
@KoEonYack

**Comment by KoEonYack** [comment]
### 2501

```js
const input = require('fs').readFileSync('/dev/stdin').toString().split(' ');
const T = input.shift();
let output = [];

for (let i = 0; i <= T; i++) {
  if (T % i === 0) output.push(i)
}

if (output.length >= input[0]) {  <--------- 검사!!
	console.log(output[input[0] - 1]);
}else{
 console.log(0);
}
```

쌤 코드 소수인 두 수인 `2 13` 을 입력하면 undefined나와용
그래서 검사 로직 추가했어요!

**Comment by leedoopal** [comment]
오와아아아아..... 쌤 드디어 해결했어요!! ㅠㅠㅠㅠ감사해요
